version: '3.8'
services:
  node:
    image: 'node:16'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 3001:3001
    command: 'npm start'